name: Deploy app

env:
  PROJECT_DIR: whodb.org
  STAGING_DIR: staging.whodb.org
  MODE: "production"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Backup current app.whodb.org
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euo pipefail
            TIMESTAMP="$(date +%Y%m%d%H%M%S)"
            mkdir -p "/home/${{ secrets.DEPLOY_USER }}/backups/${{ env.PROJECT_DIR }}"
            if [ -d "/home/${{ secrets.DEPLOY_USER }}/${{ env.PROJECT_DIR }}" ]; then
              mv "/home/${{ secrets.DEPLOY_USER }}/${{ env.PROJECT_DIR }}" "/home/${{ secrets.DEPLOY_USER }}/backups/${{ env.PROJECT_DIR }}-${TIMESTAMP}"
            fi
            cp -r "/home/${{ secrets.DEPLOY_USER }}/${{ env.STAGING_DIR }}" "/home/${{ secrets.DEPLOY_USER }}/${{ env.PROJECT_DIR }}"

      - name: Deploy specific docker-compose
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "docker-compose.yaml"
          target: "/home/${{ secrets.DEPLOY_USER }}/${{ env.PROJECT_DIR }}"

      - name: Deploy/Build with docker compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euo pipefail
            cd "/home/${{ secrets.DEPLOY_USER }}/${{ env.PROJECT_DIR }}"
            docker compose down
            echo "PORT=61999" > .env
            docker compose up --build -d web-nginx
