name: Deploy app

env:
  SERVER_USER: "w3reg"
  SERVER_IP: "135.181.202.179"
  DEPLOY_PATH: "/home/w3reg/app.whodb.org"
  BACKUP_PATH: "/home/w3reg/backups"
  STAGING_PATH: "/home/w3reg/staging.whodb.org"
  MODE: "production"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Key to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t ed25519 ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Backup current app.whodb.org
        run: |
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << EOF
            set -euo pipefail
            TIMESTAMP=\$(date +%Y%m%d%H%M%S)
            mkdir -p ${{ env.BACKUP_PATH }}
            if [ -d "${{ env.DEPLOY_PATH }}" ]; then
              mv ${{ env.DEPLOY_PATH }} ${{ env.BACKUP_PATH }}/whodb-org-\$TIMESTAMP
            fi
            cp -r ${{ env.STAGING_PATH }} ${{ env.DEPLOY_PATH }}
          EOF

      - name: Deploy specific docker-compose
        run: |
          scp docker-compose.yaml ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:${{ env.DEPLOY_PATH }}/docker-compose.yaml

      - name: Deploy/Build with docker compose
        run: |
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << EOF
            set -euo pipefail
            cd ${{ env.DEPLOY_PATH }}
            echo "NGINX_PORT=61999" > .env
            docker compose up --build -d web-nginx
          EOF
