name: Build and Deploy preproduction
env:
  NODE_VERSION: "18"
  SERVER_USER: "w3reg"
  SERVER_IP: "157.180.90.37"
  DEPLOY_PATH: "/home/w3reg/staging.whodb.org"
  VITE_APP_WALLET_CONNECT_PROJECT_ID: w3reg
  VITE_APP_DEFAULT_WS_URL: wss://people-paseo.dotters.network
  VITE_APP_DEFAULT_WS_URL_RELAY: wss://paseo.dotters.network
  VITE_APP_REGISTRAR_INDEX__PEOPLE_PASEO: 1
  VITE_APP_AVAILABLE_CHAINS: paseo_people
  VITE_APP_DEFAULT_CHAIN: paseo_people
  VITE_APP_CHALLENGES_API_URL: ${{ vars.WS_API_URL }}
  MODE: "staging"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-build-env

      - name: Build the application
        env:
          BUILD_TARGET: "production"
        run: |
          nix-shell --command "bash scripts/setup.sh"
          nix-shell --command "bash scripts/build.sh"

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add SSH Key to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t ed25519 ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
          set -euo pipefail
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << EOF 
            set -euo pipefail
            rm -fr ${{ env.DEPLOY_PATH }}/nginx || true
            rm -fr ${{ env.DEPLOY_PATH }}/dist || true
            mkdir -p ${{ env.DEPLOY_PATH }}
          EOF
          scp -r ./nginx ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:${{ env.DEPLOY_PATH }}
          scp -r ./dist ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:${{ env.DEPLOY_PATH }}
          scp docker-compose.yaml ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:${{ env.DEPLOY_PATH }}/docker-compose.yaml
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << EOF
            set -euo pipefail
            cd ${{ env.DEPLOY_PATH }}
            # stop and remove existing containers
            docker compose down --remove-orphans || true
            echo "NGINX_PORT=51999" > .env
            docker compose up --build -d
          EOF
